[[language]]
name = "typescript"
auto-format = true
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.ts",
] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.tsx",
] }
