[[language]]
name = "just"
auto-format = true

[language.formatter]
command = "just"
args = ["--justfile", "/dev/stdin", "--dump"]

[[language]]
name = "nix"
auto-format = true

[language.formatter]
command = "alejandra"

[[language]]
name = "python"
auto-format = true

[language.formatter]
command = "ruff"
args = ["format", "-"]

[[language]]
name = "toml"
auto-format = true

[language.formatter]
command = "taplo"
args = ["format", "-"]
